### ISSUE TITLE
Broken by infinite scroll

### ISSUE THREAD

**Issue by gastongouron** [edella2/eSportal#134]
On calendar: if a game if filtered (routes are changing from index_tournament to games/. and you cannot click previous/next anymore
On index: Search / sort are broken for the same reasons. We should make 9 different routes in order to have the game logic sorting + infinite scroll logic living in the controller and just append the results to a new route when a search button is hitten.

**Comment by stevula** [comment]
This is closely related to issue [117](https://github.com/edella2/eSportal/issues/117) and possibly [125](https://github.com/edella2/eSportal/issues/125)
